### ISSUE TITLE
The todo-front resource include Lab section 9.2 has no "BACKEND_HOST" variables.

### ISSUE THREAD

**Issue by buraiden-masa** [RedHatTraining/DO288-apps#210]
In section 9.2 comprehensive review, it don't specify the name of the backend pod.
Instead, use the "BACKEND_HOST" environment variable to determine where to connect the todo-frontend pod.
Lab document says:
<pre>
Set the environment variable BACKEND_HOST on the front end deployment to the service name of the todo-backend API.
</pre>

However, it seems that this environment variable is not actually used. The nginx config file sets its connection to todo-list:3000.
<pre>
[student@workstation ~]$ cd ~/DO288-apps/todo-frontend
[student@workstation todo-frontend]$ grep proxy nginx.conf
          proxy_pass http://todo-list:3000;
</pre>

This means that this lab training will fail if the name of the backend pod is not "todo-list" .
I think nginx.conf should use the appropriate environment variable, or add the steps to edit the Containerfile using actual backend pod name.

**Comment by m-czernek** [comment]
Hi @buraiden-masa ,

Thank you for reaching out! Briefly looking at the issue, I agree, it should probably be `proxy_pass http://${BACKEND_HOST}:3000;`

I'll create an internal ticket and we'll take a look at this issue soon. 

Note that the `todo-list` is not the name of a backend pod, but the OpenShift/Kubernetes Service object.
