### ISSUE TITLE
Drop/Rename the master branch

### ISSUE THREAD

**Issue by eskultety** [RedHatTraining/DO288-apps#225]
I don't have any insight on why there are both 'master' and 'main' branches in the repository, but it's incredibly confusing in the CLI when muscle memory kicks in which lead to errors in some exercises because the master branch is behind main. So please either drop or rename the master branch so that git complains if the "wrong" default is selected with checkout/switch.

**Comment by m-czernek** [comment]
Aha, good call. We must have forgotten about the `master` branch, my apologies. It seems we also have a number of other branches that needs to be cleaned up. I'll check it out and do some cleaning.

**Comment by m-czernek** [comment]
Done. Thanks for raising this issue, much appreciated!
